### ISSUE TITLE
Maybe is not good use world to reference the Window Object

### ISSUE THREAD

**Issue by woliveiras** [soutomario/AnimusJS#2]
Maybe is not good use `world` namespace to reference the Window Object because is a "convention" name the object as `win`, and Document Object as `doc` or even not rename them.

In this line:

https://github.com/soutomario/animusjs/blob/master/src/animus.js#L1

Look: https://toddmotto.com/what-function-window-document-undefined-iife-really-means/

In some lines you use window and in others use world:

* world: https://github.com/soutomario/animusjs/blob/master/src/animus.js#L9
* window: https://github.com/soutomario/animusjs/blob/master/src/animus.js#L26

Is good make a pattern in the project.

**Comment by omariosouto** [comment]
Thanks by the tip =D
Now it's [everything okay!](https://github.com/soutomario/animusjs/commit/0198cc6aa962962b2291b5adacd808ad5272cad6)
